### ISSUE TITLE
Using Redux - DevTools extension link is suspect

### ISSUE THREAD

**Issue by ppslim** [rjaros/kvision-guide#12]
In the first Info hint box, there is a link to what is suggested to be the Redux DevTools Extension.

This links looks to be suspect, redirecting solely to advertisements and what looks to predominantly be adult themed.

This looks like it was a change in the project https://github.com/zalmoxisus/redux-devtools-extension/issues/810

**Comment by rjaros** [comment]
Thanks for info! Fixed.
